#!/usr/bin/env python3
"""
Compliance Vertical: Generate All Reports
Generates PDFs and LinkedIn posts for CMP01-CMP04

Author: Mboya Jeffers
Date: 2026-01-31
"""

import pandas as pd
import json
import os
from datetime import datetime
from weasyprint import HTML, CSS

DATA_DIR = os.path.dirname(os.path.abspath(__file__)) + "/../Compliance/data"
REPORT_DIR = os.path.dirname(os.path.abspath(__file__)) + "/../Compliance/reports"
POST_DIR = os.path.dirname(os.path.abspath(__file__)) + "/../Compliance/posts"

CSS_STYLE = """
@page { margin: 0.75in; size: letter; }
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a1a; }
h1 { color: #0d1b2a; font-size: 24pt; border-bottom: 3px solid #9d4edd; padding-bottom: 10px; }
h2 { color: #9d4edd; font-size: 16pt; margin-top: 25px; border-bottom: 1px solid #e0aaff; padding-bottom: 5px; }
.header { background: linear-gradient(135deg, #3c096c 0%, #7b2cbf 100%); color: white; padding: 30px; margin: -0.75in -0.75in 30px -0.75in; }
.header h1 { color: white; border-bottom: none; margin: 0; }
.header .subtitle { color: #e0aaff; font-size: 14pt; margin-top: 10px; }
.metric-box { background: #f8f9fa; border-left: 4px solid #7b2cbf; padding: 15px; margin: 15px 0; }
.metric-value { font-size: 28pt; font-weight: bold; color: #7b2cbf; }
.metric-label { font-size: 10pt; color: #666; text-transform: uppercase; }
.grid { display: flex; flex-wrap: wrap; gap: 20px; }
.grid-item { flex: 1; min-width: 200px; }
table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 10pt; }
th { background: #7b2cbf; color: white; padding: 10px; text-align: left; }
td { padding: 8px 10px; border-bottom: 1px solid #e0e0e0; }
tr:nth-child(even) { background: #f8f9fa; }
.highlight { background: #f3e8ff; padding: 15px; border-radius: 5px; margin: 15px 0; }
.warning { background: #fef3c7; padding: 15px; border-radius: 5px; margin: 15px 0; }
.footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; font-size: 9pt; color: #666; }
"""

def generate_cmp01_reports():
    """Generate CMP-01 reports"""
    code = "CMP01"
    title = "Credit Bureau Complaint Pattern Analysis"

    with open(f"{DATA_DIR}/{code}_summary.json", 'r') as f:
        summary = json.load(f)

    # Executive Summary
    html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: {title}</h1>
        <div class="subtitle">Executive Summary | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>Key Findings</h2>
    <div class="grid">
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['complaint_volume']['total_complaints']}</div>
            <div class="metric-label">Total Complaints</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['product_breakdown']['credit_reporting_share']}</div>
            <div class="metric-label">Credit Reporting Share</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['compliance_metrics']['avg_timely_response']}</div>
            <div class="metric-label">Timely Response Rate</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['compliance_metrics']['avg_dispute_rate']}</div>
            <div class="metric-label">Consumer Dispute Rate</div>
        </div></div>
    </div>

    <div class="highlight">
        <strong>Key Insight:</strong> Credit reporting complaints dominate the consumer complaint landscape,
        representing {summary['product_breakdown']['credit_reporting_share']} of all filings. The leading bureau
        receives {summary['complaint_volume']['top_company_share']} of credit bureau complaints.
    </div>

    <h2>Complaint Volume Analysis</h2>
    <ul>
        <li><strong>Daily Average:</strong> {summary['complaint_volume']['daily_average']} complaints</li>
        <li><strong>Top Company:</strong> {summary['complaint_volume']['top_company']}</li>
        <li><strong>Top Product:</strong> {summary['product_breakdown']['top_product']}</li>
        <li><strong>Peak Periods:</strong> {summary['trend_insights']['peak_periods']}</li>
    </ul>

    <h2>Compliance Performance</h2>
    <div class="warning">
        <p><strong>Risk Score:</strong> {summary['compliance_metrics']['composite_risk_score']}</p>
        <p>Average resolution time: {summary['compliance_metrics']['avg_resolution_days']} days</p>
    </div>

    <div class="footer">
        <p><strong>Data Sources:</strong> Synthetic CFPB-style data | <strong>Author:</strong> {summary['report_metadata']['author']}</p>
        <p><em>Generated by Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=html).write_pdf(f"{REPORT_DIR}/{code}_Executive_Summary_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    # Technical Analysis
    tech_html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: Technical Analysis</h1>
        <div class="subtitle">Complaint Pattern Methodology | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>1. Data Overview</h2>
    <table>
        <tr><td><strong>Total Records</strong></td><td>{summary['report_metadata']['total_rows_processed']:,}</td></tr>
        <tr><td><strong>Companies Analyzed</strong></td><td>{summary['report_metadata']['companies_analyzed']}</td></tr>
        <tr><td><strong>Analysis Period</strong></td><td>{summary['report_metadata']['data_start'][:10]} to {summary['report_metadata']['data_end'][:10]}</td></tr>
    </table>

    <h2>2. Methodology</h2>
    <p>Complaint patterns analyzed using CFPB-style categorization with daily volume modeling including:</p>
    <ul>
        <li>Seasonal adjustment factors (tax season, holidays)</li>
        <li>Year-over-year growth trends (~8-12% annually)</li>
        <li>Bureau-specific market share distribution</li>
        <li>Product and issue category breakdowns</li>
    </ul>

    <h2>3. Risk Scoring Model</h2>
    <div class="metric-box">
        Composite Risk = (Response Risk × 0.3) + (Dispute Risk × 0.4) + (Resolution Risk × 0.3)
    </div>

    <h2>4. Key Metrics</h2>
    <table>
        <tr><th>Metric</th><th>Value</th><th>Industry Benchmark</th></tr>
        <tr><td>Timely Response Rate</td><td>{summary['compliance_metrics']['avg_timely_response']}</td><td>95%+</td></tr>
        <tr><td>Consumer Dispute Rate</td><td>{summary['compliance_metrics']['avg_dispute_rate']}</td><td><20%</td></tr>
        <tr><td>Resolution Time</td><td>{summary['compliance_metrics']['avg_resolution_days']} days</td><td><30 days</td></tr>
    </table>

    <div class="footer">
        <p><strong>Report:</strong> {code} | <strong>Version:</strong> 1.0</p>
        <p><strong>Author:</strong> {summary['report_metadata']['author']} | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=tech_html).write_pdf(f"{REPORT_DIR}/{code}_Technical_Analysis_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    # LinkedIn Post
    post = f"""# {code} LinkedIn Post
## {title}

**Copy and paste the text below:**

---

Deep dive into credit bureau complaint patterns: Analyzed {summary['report_metadata']['total_rows_processed']:,} records over 10 years.

**Key findings:**

📊 Total Complaints: {summary['complaint_volume']['total_complaints']}
📈 Daily Average: {summary['complaint_volume']['daily_average']}
🎯 Credit Reporting Share: {summary['product_breakdown']['credit_reporting_share']}
⚡ Timely Response: {summary['compliance_metrics']['avg_timely_response']}

**Compliance metrics:**
• Dispute Rate: {summary['compliance_metrics']['avg_dispute_rate']}
• Resolution Time: {summary['compliance_metrics']['avg_resolution_days']} days
• Risk Score: {summary['compliance_metrics']['composite_risk_score']}

Includes seasonal patterns, trend analysis, and risk scoring methodology.

📊 Data Source: CFPB-style synthetic data
🔧 Built with custom Python analytics pipeline

#DataEngineering #Compliance #CreditBureau #RiskManagement #CFPB

---

**Post metadata:**
- Report Code: {code}
- Generated: {datetime.now().strftime('%Y-%m-%d')}
"""

    with open(f"{POST_DIR}/{code}_LinkedIn_Post_v1.0.md", 'w') as f:
        f.write(post)

    print(f"  {code}: Executive Summary, Technical Analysis, LinkedIn Post")

def generate_cmp02_reports():
    """Generate CMP-02 reports"""
    code = "CMP02"
    title = "Large Bank Regulatory Risk Profile"

    with open(f"{DATA_DIR}/{code}_summary.json", 'r') as f:
        summary = json.load(f)

    html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: {title}</h1>
        <div class="subtitle">Executive Summary | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>Key Findings</h2>
    <div class="grid">
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['regulatory_profile']['avg_risk_score']}</div>
            <div class="metric-label">Avg Risk Score</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['enforcement_summary']['total_fines']}</div>
            <div class="metric-label">Total Fines (10Y)</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['regulatory_profile']['avg_remediation_rate']}</div>
            <div class="metric-label">Remediation Rate</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['enforcement_summary']['total_actions']}</div>
            <div class="metric-label">Enforcement Actions</div>
        </div></div>
    </div>

    <div class="warning">
        <strong>Highest Risk Category:</strong> {summary['regulatory_profile']['highest_risk_category']}
        <br><strong>Most Active Agency:</strong> {summary['enforcement_summary']['most_common_agency']}
    </div>

    <h2>Trend Insights</h2>
    <ul>
        <li><strong>Risk Trajectory:</strong> {summary['trend_insights']['risk_trajectory']}</li>
        <li><strong>Key Focus Areas:</strong> {summary['trend_insights']['key_focus_areas']}</li>
        <li><strong>Outlook:</strong> {summary['trend_insights']['regulatory_outlook']}</li>
    </ul>

    <div class="footer">
        <p><strong>Author:</strong> {summary['report_metadata']['author']} | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=html).write_pdf(f"{REPORT_DIR}/{code}_Executive_Summary_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    tech_html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: Technical Analysis</h1>
        <div class="subtitle">Regulatory Risk Methodology | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>1. Data Overview</h2>
    <table>
        <tr><td><strong>Total Records</strong></td><td>{summary['report_metadata']['total_rows_processed']:,}</td></tr>
        <tr><td><strong>Banks Analyzed</strong></td><td>{summary['report_metadata']['banks_analyzed']}</td></tr>
    </table>

    <h2>2. Regulatory Categories Analyzed</h2>
    <ul>
        <li>Consumer Protection</li><li>BSA/AML</li><li>Fair Lending</li>
        <li>Capital Requirements</li><li>Liquidity</li><li>Operational Risk</li>
        <li>Cybersecurity</li><li>Third Party Risk</li>
    </ul>

    <h2>3. Enforcement Summary</h2>
    <p>Total fines of {summary['enforcement_summary']['total_fines']} across {summary['enforcement_summary']['total_actions']} actions.</p>

    <div class="footer">
        <p><strong>Report:</strong> {code} | <strong>Version:</strong> 1.0 | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=tech_html).write_pdf(f"{REPORT_DIR}/{code}_Technical_Analysis_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    post = f"""# {code} LinkedIn Post
## {title}

---

Regulatory risk analysis for large banks: {summary['report_metadata']['total_rows_processed']:,} data points analyzed.

**Key findings:**

📊 Avg Risk Score: {summary['regulatory_profile']['avg_risk_score']}
💰 Total Fines: {summary['enforcement_summary']['total_fines']}
🎯 Remediation Rate: {summary['regulatory_profile']['avg_remediation_rate']}
⚖️ Enforcement Actions: {summary['enforcement_summary']['total_actions']}

**Highest risk:** {summary['regulatory_profile']['highest_risk_category']}
**Trajectory:** {summary['trend_insights']['risk_trajectory']}

#DataEngineering #Compliance #Banking #RiskManagement #Regulatory

---
- Report: {code} | Generated: {datetime.now().strftime('%Y-%m-%d')}
"""

    with open(f"{POST_DIR}/{code}_LinkedIn_Post_v1.0.md", 'w') as f:
        f.write(post)

    print(f"  {code}: Executive Summary, Technical Analysis, LinkedIn Post")

def generate_cmp03_reports():
    """Generate CMP-03 reports"""
    code = "CMP03"
    title = "Consumer Credit Compliance Trends"

    with open(f"{DATA_DIR}/{code}_summary.json", 'r') as f:
        summary = json.load(f)

    html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: {title}</h1>
        <div class="subtitle">Executive Summary | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>Key Findings</h2>
    <div class="grid">
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['complaint_metrics']['total_complaints']}</div>
            <div class="metric-label">Total Complaints</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['compliance_scores']['industry_avg_score']}</div>
            <div class="metric-label">Industry Compliance Score</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['complaint_metrics']['avg_resolution_rate']}</div>
            <div class="metric-label">Resolution Rate</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['enforcement_summary']['total_fines']}</div>
            <div class="metric-label">Total Fines</div>
        </div></div>
    </div>

    <div class="highlight">
        <strong>Best Performer:</strong> {summary['compliance_scores']['best_performer']}
        <br><strong>Top Issuer by Volume:</strong> {summary['complaint_metrics']['top_issuer']}
    </div>

    <h2>Monetary Relief</h2>
    <p>Total consumer monetary relief: {summary['complaint_metrics']['total_monetary_relief']}</p>

    <div class="footer">
        <p><strong>Author:</strong> {summary['report_metadata']['author']} | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=html).write_pdf(f"{REPORT_DIR}/{code}_Executive_Summary_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    tech_html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: Technical Analysis</h1>
        <div class="subtitle">Consumer Credit Methodology | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>1. Data Overview</h2>
    <table>
        <tr><td><strong>Total Records</strong></td><td>{summary['report_metadata']['total_rows_processed']:,}</td></tr>
        <tr><td><strong>Issuers Analyzed</strong></td><td>{summary['report_metadata']['issuers_analyzed']}</td></tr>
    </table>

    <h2>2. Compliance Scoring</h2>
    <p>Compliance scores based on resolution rates, speed, and complaint volumes.</p>
    <p>Industry average: {summary['compliance_scores']['industry_avg_score']}</p>
    <p>Improvement trend: {summary['compliance_scores']['improvement_trend']}</p>

    <div class="footer">
        <p><strong>Report:</strong> {code} | <strong>Version:</strong> 1.0 | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=tech_html).write_pdf(f"{REPORT_DIR}/{code}_Technical_Analysis_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    post = f"""# {code} LinkedIn Post
## {title}

---

Consumer credit compliance analysis: {summary['report_metadata']['total_rows_processed']:,} records analyzed.

📊 Total Complaints: {summary['complaint_metrics']['total_complaints']}
🎯 Compliance Score: {summary['compliance_scores']['industry_avg_score']}
✅ Resolution Rate: {summary['complaint_metrics']['avg_resolution_rate']}
💰 Monetary Relief: {summary['complaint_metrics']['total_monetary_relief']}

Best performer: {summary['compliance_scores']['best_performer']}

#DataEngineering #Compliance #ConsumerCredit #FinTech

---
- Report: {code} | Generated: {datetime.now().strftime('%Y-%m-%d')}
"""

    with open(f"{POST_DIR}/{code}_LinkedIn_Post_v1.0.md", 'w') as f:
        f.write(post)

    print(f"  {code}: Executive Summary, Technical Analysis, LinkedIn Post")

def generate_cmp04_reports():
    """Generate CMP-04 reports"""
    code = "CMP04"
    title = "Systemically Important Bank Compliance Monitor"

    with open(f"{DATA_DIR}/{code}_summary.json", 'r') as f:
        summary = json.load(f)

    html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: {title}</h1>
        <div class="subtitle">Executive Summary | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>Capital Adequacy</h2>
    <div class="grid">
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['capital_adequacy']['avg_cet1_ratio']}</div>
            <div class="metric-label">Avg CET1 Ratio</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['capital_adequacy']['avg_lcr']}</div>
            <div class="metric-label">Avg LCR</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['stress_testing']['pass_rate']}</div>
            <div class="metric-label">Stress Test Pass Rate</div>
        </div></div>
        <div class="grid-item"><div class="metric-box">
            <div class="metric-value">{summary['resolution_readiness']['satisfactory_plans']}</div>
            <div class="metric-label">Satisfactory Resolution Plans</div>
        </div></div>
    </div>

    <h2>Risk Profile</h2>
    <div class="warning">
        <p><strong>Average Risk Score:</strong> {summary['risk_profile']['avg_risk_score']}</p>
        <p><strong>Highest Risk Category:</strong> {summary['risk_profile']['highest_risk_category']}</p>
        <p><strong>Control Effectiveness:</strong> {summary['risk_profile']['avg_control_effectiveness']}</p>
    </div>

    <h2>Stress Testing Results</h2>
    <ul>
        <li>Severely Adverse Loss Rate: {summary['stress_testing']['avg_severely_adverse_loss']}</li>
        <li>Min CET1 Under Stress: {summary['stress_testing']['min_cet1_stress']}</li>
    </ul>

    <div class="footer">
        <p><strong>Author:</strong> {summary['report_metadata']['author']} | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=html).write_pdf(f"{REPORT_DIR}/{code}_Executive_Summary_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    tech_html = f"""
    <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>
    <div class="header">
        <h1>{code}: Technical Analysis</h1>
        <div class="subtitle">SIFI Monitoring Methodology | {datetime.now().strftime('%B %d, %Y')}</div>
    </div>

    <h2>1. G-SIB Framework</h2>
    <p>Analysis covers {summary['report_metadata']['banks_analyzed']} Global Systemically Important Banks.</p>

    <h2>2. Capital Metrics</h2>
    <table>
        <tr><th>Metric</th><th>Average</th><th>Requirement</th></tr>
        <tr><td>CET1 Ratio</td><td>{summary['capital_adequacy']['avg_cet1_ratio']}</td><td>4.5% + buffers</td></tr>
        <tr><td>Leverage Ratio</td><td>{summary['capital_adequacy']['avg_leverage_ratio']}</td><td>5%+</td></tr>
        <tr><td>LCR</td><td>{summary['capital_adequacy']['avg_lcr']}</td><td>100%+</td></tr>
        <tr><td>G-SIB Surcharge</td><td>{summary['capital_adequacy']['avg_gsib_surcharge']}</td><td>1-3.5%</td></tr>
    </table>

    <h2>3. Resolution Readiness</h2>
    <p>Separability Score: {summary['resolution_readiness']['avg_separability']}</p>

    <div class="footer">
        <p><strong>Report:</strong> {code} | <strong>Version:</strong> 1.0 | <em>Mboya Jeffers - Data Engineering Portfolio</em></p>
    </div>
    </body></html>
    """

    HTML(string=tech_html).write_pdf(f"{REPORT_DIR}/{code}_Technical_Analysis_v1.0.pdf", stylesheets=[CSS(string=CSS_STYLE)])

    post = f"""# {code} LinkedIn Post
## {title}

---

G-SIB compliance monitoring: {summary['report_metadata']['banks_analyzed']} systemically important banks analyzed.

**Capital adequacy:**
📊 CET1 Ratio: {summary['capital_adequacy']['avg_cet1_ratio']}
💧 LCR: {summary['capital_adequacy']['avg_lcr']}
🎯 G-SIB Surcharge: {summary['capital_adequacy']['avg_gsib_surcharge']}

**Stress testing:**
✅ Pass Rate: {summary['stress_testing']['pass_rate']}
📉 Severely Adverse Loss: {summary['stress_testing']['avg_severely_adverse_loss']}

**Resolution:** {summary['resolution_readiness']['satisfactory_plans']} satisfactory plans

#DataEngineering #GSIB #BankingRegulation #StressTesting #Compliance

---
- Report: {code} | Generated: {datetime.now().strftime('%Y-%m-%d')}
"""

    with open(f"{POST_DIR}/{code}_LinkedIn_Post_v1.0.md", 'w') as f:
        f.write(post)

    print(f"  {code}: Executive Summary, Technical Analysis, LinkedIn Post")

def main():
    print("=" * 60)
    print("Compliance Vertical: Generating All Reports")
    print("=" * 60)

    os.makedirs(REPORT_DIR, exist_ok=True)
    os.makedirs(POST_DIR, exist_ok=True)

    print("\nGenerating reports...")
    generate_cmp01_reports()
    generate_cmp02_reports()
    generate_cmp03_reports()
    generate_cmp04_reports()

    print("\n" + "=" * 60)
    print("All Compliance reports generated successfully!")
    print("=" * 60)

if __name__ == "__main__":
    main()
